# https://docs.sonarcloud.io/advanced-setup/automatic-analysis/#additional-analysis-configuration
sonar.organization=mtes-mct
sonar.projectKey=MTES-MCT_monitor-field
sonar.host.url=https://sonarcloud.io
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/__tests__/**,**/*.test.ts,**/*.test.tsx
sonar.exclusions=android/**,ios/**,coverage/**,node_modules/**,.expo/**,data/tiles/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8



