# https://docs.sonarcloud.io/advanced-setup/automatic-analysis/#additional-analysis-configuration
sonar.organization=mtes-mct
sonar.projectKey=MTES-MCT_monitorfield
sonar.host.url=https://sonarcloud.io
sonar.sources=src
sonar.exclusions=android/**,ios/**,coverage/**,node_modules/**,.expo/**,data/tiles/**
sonar.sourceEncoding=UTF-8