
name: Android Development Build

on:
  workflow_dispatch:

env:
  NODE_VERSION: "24"
  JAVA_VERSION: "17"

concurrency:
  group: android-development-build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-android-development:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm

      - name: Setup Java
        uses: actions/setup-java@v5.2.0
        with:
          distribution: temurin
          java-version: "17"

      - name: Install dependencies
        run: npm ci

      - name: Setup Expo and EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Trigger EAS Android development build
        run: npx eas build --platform android --profile development --non-interactive